### ISSUE TITLE
When having the autocomplete focussed, it's impossible to scroll.

### ISSUE THREAD

**Issue by Rubenvdveen** [web-ridge/react-native-paper-autocomplete#7]
When having the autocomplete focussed, it's impossible to scroll.

Video:
https://youtu.be/0yGnSWfeleM

**Comment by RichardLindhout** [comment]
This issue is fixed now on the web! 

On small native devices we will probably use https://github.com/gorhom/react-native-bottom-sheet in the future because dropdown is not so user friendly on small screens.

The scroll issue can't be fixed though on tablets (in native apps) as far a I know.

https://twitter.com/RichardLindhout/status/1481579845838675969
